---
# handlers file for haproxy

- name: Reboot
  ansible.builtin.reboot:

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
    daemon_reload: true

- name: Test Config
  ansible.builtin.command: haproxy -f /etc/haproxy/haproxy.cfg -c
  changed_when: false
